HomeWork_13/HomeWork_13/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fin_assist.urls'))
]

HomeWork_13/fin_assist/urls.py
from django.urls import path
from . import views

app_name = 'fin_assist'

urlpatterns = [
    path('', views.main, name='main'),
    path('categories/', views.pay_categories, name='pay_categories'),
    path('categories/edit/<int:cat_id>', views.edit_pay_categories, name='edit_pay_categories'),
    path('categories/delete/<int:cat_id>', views.delete_pay_categories, name='delete_pay_categories'),
]

HomeWork_13/fin_assist/models.py
from django.db import models


class FinCategory(models.Model):
    name = models.CharField(max_length=32, blank=False, null=False, unique=True, verbose_name="Name")
    description = models.CharField(max_length=128, blank=True, null=True, verbose_name="Description")
    created_on = models.DateTimeField(auto_now_add=True, null=False)

    def __str__(self):
        return self.name

HomeWork_13/fin_assist/views.py
from django.shortcuts import render, redirect
from . models import FinCategory
from django.contrib import messages


def main(request):
    return render(request, 'fin_assist/index.html', {})


def pay_categories(request):
    if request.method == 'POST':
        filter_str = request.POST["filter_str"]
    else:
        filter_str = ""

    if filter_str:
        categories = FinCategory.objects.filter(name__icontains=filter_str).order_by("name")
    else:
        categories = FinCategory.objects.all().order_by("name")

    return render(request, 'fin_assist/pay_categories.html',
                  context={"filter_str": filter_str, "categories": categories})


def edit_pay_categories(request, cat_id):
    if request.method == 'POST':
        try:
            if cat_id == 0:
                cat = FinCategory(
                    name=request.POST['cat_name'],
                    description=request.POST['cat_desc']
                )
                cat.save()
            else:
                cat = FinCategory.objects.get(pk=cat_id)
                print(cat.name)
                cat.name = request.POST['cat_name']
                cat.description = request.POST['cat_desc']
                cat.save()

            messages.add_message(request, messages.SUCCESS, "Operation was successful", "success")
        except Exception as err:
            messages.add_message(request, messages.ERROR, f"Operation was aborted: {str(err)}", "danger")
    return redirect('/categories/')


def delete_pay_categories(request, cat_id):
    try:
        cat = FinCategory.objects.get(pk=cat_id)
        cat.delete()
        messages.add_message(request, messages.SUCCESS, "Operation was successful", "success")
    except Exception as err:
        messages.add_message(request, messages.ERROR, f"Operation was aborted: {str(err)}", "danger")
    return redirect('/categories/')

HomeWork_13/templates/fin_assist/base.html
<!DOCTYPE html>
<html lang="en">
{#<head>#}
{#  <title>Bootstrap Example</title>#}
{#  <meta charset="utf-8">#}
{#  <meta name="viewport" content="width=device-width, initial-scale=1">#}
{#  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">#}
{#  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>#}
{#</head>#}
{#<body>#}
{##}
{#<div class="container mt-3">#}
{#  <h2>Select Menu</h2>#}
{#  <p>To style a select menu in Bootstrap 5, add the .form-select class to the select element:</p>#}
{#  <form action="/action_page.php">#}
{#    <label for="sel1" class="form-label">Select list (select one):</label>#}
{#    <select class="form-select" id="sel1" name="sellist1">#}
{#      <option>1</option>#}
{#      <option>2</option>#}
{#      <option>3</option>#}
{#      <option>4</option>#}
{#    </select>#}
{#    <br>#}
{##}
{#    <label for="sel2" class="form-label">Mutiple select list (hold shift to select more than one):</label>#}
{#    <select multiple class="form-select" id="sel2" name="sellist2">#}
{#      <option>1</option>#}
{#      <option>2</option>#}
{#      <option>3</option>#}
{#      <option>4</option>#}
{#      <option>5</option>#}
{#    </select>#}
{#    <button type="submit" class="btn btn-primary mt-3">Submit</button>#}
{#  </form>#}
{#</div>#}
{##}
{#</body>#}
{#</html>#}
<head>
  <meta charset="UTF-8"/>

  <title>Free assist</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

{#  <link rel="stylesheet" href="/static/fin_assist/style.css"/>#}
{#  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}"/>#}

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
          crossorigin="anonymous"></script>

  {% load static %}
  <link rel="stylesheet" href="{% static 'fin_assist/style.css' %}">
</head>
<body>
  <div class="row" id="nav-bar">
    <div class="col-md-12">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="navbar-brand">FREE ASSISTANT</div>
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/contacts">Contacts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/categories">Categories</a>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </div>
{#  <!-- Start Container -->#}
{#  <div class="container pt-1">#}
{#    <!-- Start Header -->#}
{#    <div class="row" id="header">#}
{#      <!-- Logo -->#}
{#      <div class="col-md-9">#}
{#        <h1>Сервіс Обліку Студентів</h1>#}
{#      </div>#}
{#      <!-- Groups Selector -->#}
{#      <div class="col-md-3" id="group-selector">#}
{#        <label for="sel1" class="form-label"> <strong>Група:</strong></label>#}
{#        <select class="form-select" id="sel1" name="sellist1">#}
{#          <option value="">Усі Студенти</option>#}
{#          <option value="">МтМ - 21, Подоба Віталій (№ 254)</option>#}
{#          <option value="">МтМ - 22, Корост Андрій (№ 2123)</option>#}
{#        </select>#}
{#      </div>#}
{#    </div>#}
{#    <!-- End Header -->#}
{##}
{#    <!-- Start SubHeader -->#}
{#    <!-- End SubHeader -->#}
{##}
{#    <!-- Start Main Page Content -->#}
{#    <div class="row" id="content-columns">#}
{#      <div class="col-sm-12" id="content-column">#}
{#        Контент, Список Студентів#}
{#      </div>#}
{##}
{#    </div>#}
{#    <!-- End Main Page Content -->#}
{##}
{#    <!-- Start Footer -->#}
{#    <div class="row" id="footer">#}
{#      <div class="col-sm-12">#}
{#        &copy; 2014 Сервіс Обліку Студентів#}
{#      </div>#}
{#    </div>#}
{#    <!-- End Footer -->#}
{#  </div>#}
{#  <!-- End Container -->#}
{##}
  <main class="template" role="main">
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

HomeWork_13/templates/fin_assist/index.html
{% extends "fin_assist/base.html" %}
{% block content %}
  <div class="container pt-2">
    <p
        class="d-flex flex-column align-items-center justify-content-center bg-secondary"
        style="height: 50px; color: #ffffff"
    >
      <strong>Welcome to Free Assistant</strong>
    </p>
  </div>
{% endblock %}

HomeWork_13/templates/fin_assist/pay_categories.html
{% extends "fin_assist/base.html" %}
{% block content %}
  <div class="container mt-2">
    <p
        class="d-flex flex-column align-items-center justify-content-center bg-secondary"
        style="height: 50px; color: #ffffff"
    >
      <strong>Categories</strong>
    </p>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-sm-2"></div>
      <div class="col-sm-8">
        <nav class="navbar">
          <div class="d-flex justify-content-start">
            <form class="d-flex" action="{% url 'fin_assist:pay_categories' %}" method="POST">
              {% csrf_token %}
              <input class="form-control me-2" id="filter_str" type="search" name="filter_str"
                     placeholder="Search" aria-label="Search" value={{ filter_str }}>
              <button class="btn btn-outline-success" type="submit">Refresh</button>
            </form>
          </div>

          <div class='d-flex justify-content-end'>
            <button type="button" class="btn btn-outline-primary"
                    data-bs-toggle="modal"
                    data-bs-target="#EditCategory"
                    data-bs-header="Adding a category"
                    data-bs-cat_id="0"
                    data-bs-cat_name=""
                    data-bs-cat_desc=""
            >
              Add category
            </button>
          </div>
        </nav>

        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.extra_tags }} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}

        <table class="table table-bordered table-striped" id="ContactsTable">
          <thead class="table-dark">
          <tr>
            <th style="width: 10%">Id</th>
            <th style="width: 30%">Name</th>
            <th style="width: 50%">Description</th>
            <th style="width: 10%" colspan="2">Action</th>
          </tr>
          </thead>
          <tbody>
            {% for cat in categories %}
              <tr>
                <td class="text-end">{{ cat.id }}</td>
                <td class="text-start">{{ cat.name }}</td>
                <td class="text-start">{{ cat.description }}</td>
                <td>
                  <button type="button" class="btn btn-outline-primary btn-sm"
                          data-bs-toggle="modal"
                          data-bs-target="#EditCategory"
                          data-bs-header="Editing a category"
                          data-bs-cat_id="{{ cat.id }}"
                          data-bs-cat_name="{{ cat.name }}"
                          data-bs-cat_desc="{{ cat.description }}"
                  >
                    <span class="btn-label"><i class="fa fa-edit"></i></span></button>
                </td>
                <td>
                  <button type="button" class="btn btn-outline-danger btn-sm"
                          data-bs-toggle="modal"
                          data-bs-target="#DeleteCategory"
                          data-bs-header="{{ cat.name }}"
                          data-bs-cat_id="{{ cat.id }}"
                  >
                    <span class="btn-label"><i class="fa fa-trash"></i></span></button>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="col-sm-2"></div>
    </div>
  </div>

  <!-- Modal 1 for updating a category -->
  <div class="modal fade" id="EditCategory" tabindex="-1" aria-labelledby="EditCategoryLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="EditCategoryLabel">Adding a category</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form class="needs-validation" id="form_action_edit" action="{% url 'fin_assist:edit_pay_categories' 0 %}"
              method="POST" novalidate>
          {% csrf_token %}
          <div class="modal-body">
            <div class="form-group">
              <label for="cat_name" class="control-label">
                <span style="font-weight:bold">Name</span>
              </label>
              <input type="text" id="cat_name" class="form-control" name="cat_name" autocomplete="off" required
                     value=""/>
              <div class="invalid-feedback">
                Enter a category name
              </div>
            </div>
            <div class="form-group">
              <label for="cat_desc" class="control-label">
                <span style="font-weight:bold">Description</span>
              </label>
              <input type="text" id="cat_desc" class="form-control" name="cat_desc" autocomplete="off"
                     value=""/>
            </div>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Save changes</button>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- end Modal 1 -->

  <!-- Modal 2 for deleting a note -->
  <div class="modal fade" id="DeleteCategory" tabindex="-1" aria-labelledby="basicModalLabel"
       aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="basicModalLabel">Deleting a category</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <label class="col-xs-2 control-label">Do you want to
            <span style="font-weight:bold;color:red">delete</span> a category ?
          </label>
        </div>
        <div class="modal-footer">
          <form id="form_action_delete" action="{% url 'fin_assist:delete_pay_categories' 0 %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <!-- End Modal 2-->

  <script>
      const updateCategory = document.getElementById("EditCategory")
      {#alert(updateNote)#}

      updateCategory.addEventListener("show.bs.modal", event => {
          const button = event.relatedTarget

          const catId = button.getAttribute("data-bs-cat_id")
          const formAction = updateCategory.querySelector('#form_action_edit')
          const action_str = "{% url 'fin_assist:edit_pay_categories' 0 %}".slice(0, -1) + catId
          formAction.setAttribute("action", action_str)

          const modalHeader = updateCategory.querySelector(".modal-title")
          modalHeader.textContent = button.getAttribute("data-bs-header")

          const modalName = updateCategory.querySelector("#cat_name")
          modalName.value = button.getAttribute("data-bs-cat_name")

          const modalDesc = updateCategory.querySelector("#cat_desc")
          modalDesc.value = button.getAttribute("data-bs-cat_desc")
      })

      const deleteCategory = document.getElementById("DeleteCategory")
      deleteCategory.addEventListener("show.bs.modal", event => {
          const button = event.relatedTarget

          const catId = button.getAttribute("data-bs-cat_id")
          const formAction = deleteCategory.querySelector('#form_action_delete')
          const action_str = "{% url 'fin_assist:delete_pay_categories' 0 %}".slice(0, -1) + catId
          formAction.setAttribute("action", action_str)

          const modalHeader = deleteCategory.querySelector(".modal-title")
          modalHeader.textContent = button.getAttribute("data-bs-header")
      })

  </script>

  <script>
      (() => {
          'use strict'

          const forms = document.querySelectorAll('.needs-validation')

          Array.from(forms).forEach(form => {
              form.addEventListener('submit', event => {

                  if (!form.checkValidity()) {
                      event.preventDefault()
                      event.stopPropagation()
                  }

                  form.classList.add('was-validated')
              }, false)
          })
      })()
  </script>
{% endblock %}